In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import csv
import pickle
import collections

/Users/georgemcintire/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/georgemcintire/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

In [2]:
plt.style.use("fivethirtyeight")

In [3]:
!ls

538 Linear regression
538_README.md
538_analysis_notebook.ipynb
538_police_killings.csv
COUNTED_README.txt
Counted_Data_Analysis.ipynb
TK TK TK.ipynb
Ultimate database 2013-2015.ipynb
WP_Fatal_Police_Shootings.csv
Washington Post Data Analysis.ipynb
ardpdqp.pdf
counted_reformat.csv
counted_reformat.numbers
county_ids.html
data-police-shootings
fatal_encounters_data.ipynb
fatal_encounters_form_responses.csv
graphics
mapping-violence.html
mapping_violence_13_15_Police Killings.csv
police-locals.csv
state_np.csv
state_np.pkl
state_per_capita_rate.csv
the-counted-2015.csv
the-counted-2016.csv

In [4]:
from IPython.core.display import HTML
css = open('/Users/georgemcintire/Data Science:Python/pycon-pandas-tutorial/style-table.css').read() + open('/Users/georgemcintire/Data Science:Python/pycon-pandas-tutorial/style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

In [5]:
counted15 = pd.read_csv("the-counted-2015.csv")

In [6]:
counted16 = pd.read_csv("the-counted-2016.csv")

In [7]:


counted15["date"] = counted15.month + "-" + counted15.day.astype(str) + "-" + counted15.year.astype(str)


counted15["date"] = pd.to_datetime(counted15["date"])

In [8]:


counted16["date"] = counted16.month + "-" + counted16.day.astype(str) + "-" + counted16.year.astype(str)


counted16["date"] = pd.to_datetime(counted16["date"])

In [9]:
counted15.shape

(1140, 15)

In [10]:
counted16.shape

(202, 15)

In [11]:
counted = pd.concat([counted15, counted16])

In [12]:
counted.reset_index(inplace=True)

In [13]:
del counted["month"]
del counted["day"]

In [14]:
#Five Thirty data import

In [15]:
fivethirtyeight = pd.read_csv("538_police_killings.csv")

In [16]:
fivethirtyeight.head()

,name,age,gender,raceethnicity,month,day,year,streetaddress,city,state,...,share_hispanic,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college
0,A'donte Washington,16,Male,Black,February,23,2015,Clearview Ln,Millbrook,AL,...,5.6,28375,51367,54766,0.937936,3,3,14.1,0.097686,0.168510
1,Aaron Rutledge,27,Male,White,April,2,2015,300 block Iris Park Dr,Pineville,LA,...,0.5,14678,27972,40930,0.683411,2,1,28.8,0.065724,0.111402
2,Aaron Siler,26,Male,White,March,14,2015,22nd Ave and 56th St,Kenosha,WI,...,16.8,25286,45365,54930,0.825869,2,3,14.6,0.166293,0.147312
3,Aaron Valdez,25,Male,Hispanic/Latino,March,11,2015,3000 Seminole Ave,South Gate,CA,...,98.8,17194,48295,55909,0.863814,3,3,11.7,0.124827,0.050133
4,Adam Jovicic,29,Male,White,March,19,2015,364 Hiwood Ave,Munroe Falls,OH,...,1.7,33954,68785,49669,1.384868,5,4,1.9,0.063550,0.403954

In [17]:
fivethirtyeight["date"] = fivethirtyeight.month + "-" + fivethirtyeight.day.astype(str) + "-" + fivethirtyeight.year.astype(str)
fivethirtyeight["date"] = pd.to_datetime(fivethirtyeight["date"])

In [18]:
del fivethirtyeight["month"], fivethirtyeight["day"]

In [19]:
fivethirtyeight.head()

,name,age,gender,raceethnicity,year,streetaddress,city,state,latitude,longitude,...,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college,date
0,A'donte Washington,16,Male,Black,2015,Clearview Ln,Millbrook,AL,32.529577,-86.362829,...,28375,51367,54766,0.937936,3,3,14.1,0.097686,0.168510,2015-02-23
1,Aaron Rutledge,27,Male,White,2015,300 block Iris Park Dr,Pineville,LA,31.321739,-92.434860,...,14678,27972,40930,0.683411,2,1,28.8,0.065724,0.111402,2015-04-02
2,Aaron Siler,26,Male,White,2015,22nd Ave and 56th St,Kenosha,WI,42.583560,-87.835710,...,25286,45365,54930,0.825869,2,3,14.6,0.166293,0.147312,2015-03-14
3,Aaron Valdez,25,Male,Hispanic/Latino,2015,3000 Seminole Ave,South Gate,CA,33.939298,-118.219463,...,17194,48295,55909,0.863814,3,3,11.7,0.124827,0.050133,2015-03-11
4,Adam Jovicic,29,Male,White,2015,364 Hiwood Ave,Munroe Falls,OH,41.148575,-81.429878,...,33954,68785,49669,1.384868,5,4,1.9,0.063550,0.403954,2015-03-19

In [20]:
fivethirtyeight.sort("date", inplace=True)

/Users/georgemcintire/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [21]:
fivethirtyeight.head()

,name,age,gender,raceethnicity,year,streetaddress,city,state,latitude,longitude,...,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college,date
170,Garrett Gagne,22,Male,White,2015,Crowell Rd and Tipcart Dr,Chatham,MA,41.684818,-69.966423,...,31641,67059,60526,1.107937,4,4,7.7,0.096795,0.527820,2015-01-01
316,Matthew Ajibade,22,Male,Black,2015,1050 Carl Griffin Dr,Savannah,GA,32.066692,-81.167877,...,25190,33545,45794,0.732520,2,1,30.1,0.119608,0.202454,2015-01-01
390,Roberto Ornelas,18,Male,Hispanic/Latino,2015,39 N Marlin Ave,Key Largo,FL,25.155903,-80.390259,...,25977,54219,53607,1.011416,3,3,16.4,0.081263,0.313959,2015-01-01
297,Lewis Lembke,47,Male,White,2015,4505 SW Masters Loop,Aloha,OR,45.486691,-122.891251,...,29959,56020,64180,0.872858,2,3,8.8,0.135548,0.174887,2015-01-02
438,Tim Elliott,53,Male,Unknown,2015,600 E Island Lake Dr,Shelton,WA,47.246532,-123.119499,...,18999,39495,48755,0.810071,1,2,18.4,0.064193,0.091158,2015-01-02

In [22]:
fivethirtyeight.reset_index(inplace=True)

In [23]:
fivethirtyeight

,index,name,age,gender,raceethnicity,year,streetaddress,city,state,latitude,...,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college,date
0,170,Garrett Gagne,22,Male,White,2015,Crowell Rd and Tipcart Dr,Chatham,MA,41.684818,...,31641,67059,60526,1.107937,4,4,7.7,0.096795,0.527820,2015-01-01
1,316,Matthew Ajibade,22,Male,Black,2015,1050 Carl Griffin Dr,Savannah,GA,32.066692,...,25190,33545,45794,0.732520,2,1,30.1,0.119608,0.202454,2015-01-01
2,390,Roberto Ornelas,18,Male,Hispanic/Latino,2015,39 N Marlin Ave,Key Largo,FL,25.155903,...,25977,54219,53607,1.011416,3,3,16.4,0.081263,0.313959,2015-01-01
3,297,Lewis Lembke,47,Male,White,2015,4505 SW Masters Loop,Aloha,OR,45.486691,...,29959,56020,64180,0.872858,2,3,8.8,0.135548,0.174887,2015-01-02
4,438,Tim Elliott,53,Male,Unknown,2015,600 E Island Lake Dr,Shelton,WA,47.246532,...,18999,39495,48755,0.810071,1,2,18.4,0.064193,0.091158,2015-01-02
5,329,Michael Kocher Jr,19,Male,White,2015,2600 Kaumualii Hwy,Kaumakani,HI,21.933861,...,30533,72000,62052,1.160317,5,4,5.4,0.045591,0.182048,2015-01-03
6,245,John Quintero,23,Male,Hispanic/Latino,2015,500 North Oliver Ave,Wichita,KS,37.693938,...,22016,36701,49865,0.736007,2,2,24.1,0.106900,0.206731,2015-01-03
7,319,Matthew Hoffman,32,Male,White,2015,630 Valencia St,San Francisco,CA,37.762848,...,64657,115750,75604,1.531004,5,5,8.6,0.050442,0.794070,2015-01-04
8,280,Kenneth Brown,18,Male,White,2015,NaN,Guthrie,OK,35.880119,...,16463,41901,53591,0.781866,2,2,33.3,0.105769,0.105675,2015-01-04
9,281,Kenneth Buck,22,Male,Hispanic/Latino,2015,E Knox Rd,Chandler,AZ,33.326981,...,32211,53346,53596,0.995335,3,3,8.5,0.069219,0.269217,2015-01-05
10,334,Michael Rodriguez,39,Male,Hispanic/Latino,2015,818 31st St,Evans,CO,40.384045,...,18022,27500,57180,0.480937,1,1,42.7,0.121156,0.062255,2015-01-05
11,44,Autumn Steele,34,Female,White,2015,104 N Garfield Ave,Burlington,IA,40.810028,...,15488,26964,42451,0.635179,1,1,26.3,0.105964,0.096565,2015-01-06
12,295,Leslie Sapp III,47,Male,Black,2015,Redlyn St,Pittsburgh,PA,40.413045,...,18978,32625,51366,0.635148,2,1,30.5,0.102180,0.083579,2015-01-06
13,60,Brian Pickett,26,Male,Black,2015,1600 E 123rd St,Los Angeles,CA,33.920825,...,17893,38690,55909,0.692017,2,2,23.6,0.214183,0.198358,2015-01-06
14,356,Patrick Wetter,25,Male,White,2015,800 Howard St,Stockton,CA,37.929747,...,15628,44228,53380,0.828550,2,2,29.4,0.265224,0.049474,2015-01-06
15,61,Brock Nichols,35,Male,White,2015,2388 E Kansas Hwy 4,Assaria,KS,38.711232,...,31080,57244,47215,1.212411,4,4,9.5,0.041357,0.240897,2015-01-06
16,395,Ronald Sneed,32,Male,Black,2015,300 Yaupon St,Freeport,TX,28.955222,...,24236,48635,67603,0.719421,2,3,18.4,0.128144,0.077155,2015-01-07
17,259,Joseph Caffarello,31,Male,White,2015,6100 Scott St,Rosemont,IL,41.989737,...,27172,46048,54548,0.844174,3,3,11.5,0.095055,0.131665,2015-01-07
18,347,Nicholas Brickman,30,Male,White,2015,SE 4th St and Scott Ave,Des Moines,IA,41.581040,...,16071,29375,59018,0.497730,1,1,31.3,0.127948,0.042051,2015-01-07
19,21,Andre Murphy Sr,42,Male,Black,2015,1223 Omaha Ave,Norfolk,NE,42.018525,...,23342,54809,46566,1.177018,4,3,10.3,0.035221,0.258886,2015-01-07
20,182,Hashim Abdul-Rasheed,41,Male,Black,2015,4600 International Gateway,Columbus,OH,39.997512,...,-,NaN,50877,NaN,NaN,NaN,-,NaN,NaN,2015-01-07
21,353,Omarr Jackson,37,Male,Black,2015,Lasalle St and Josephine St,New Orleans,LA,29.941250,...,9353,15293,37146,0.411700,1,1,54.6,0.324444,0.039320,2015-01-08
22,196,James Barker,42,Male,White,2015,600 Second Ave,Salt Lake City,UT,40.771666,...,30391,44638,60555,0.737148,2,2,18.3,0.036533,0.638550,2015-01-08
23,434,Thomas Hamby,49,Male,White,2015,2964 W 2125 S,Syracuse,UT,41.083263,...,36216,81064,69707,1.162925,4,5,4.4,0.046354,0.341968,2015-01-08
24,40,Artago Howard,36,Male,Black,2015,9661 Strong Hwy,Strong,AR,33.111282,...,17853,32614,37435,0.871217,2,1,15.6,0.055732,0.100468,2015-01-08
25,299,Loren Simpson,28,Male,White,2015,3618 White Buffalo Rd,Huntley,MT,45.863064,...,28125,68949,51342,1.342936,5,4,9.5,0.049460,0.300439,2015-01-08
26,236,Jimmy Foreman,71,Male,Unknown,2015,422 SE 3rd St,England,AR,34.542649,...,18750,31458,52582,0.598266,1,1,32.9,0.137774,0.132465,2015-01-09
27,29,Andy Martinez,33,Male,Hispanic/Latino,2015,4400 Tetons Dr,El Paso,TX,31.857638,...,13231,17388,40157,0.433000,1,1,58.1,0.144613,0.047240,2015-01-09
28,58,Brian Barbosa,23,Male,Unknown,2015,8900 Kauffman Ave,South Gate,CA,33.952348,...,18047,43750,55909,0.782522,2,2,16.3,0.125765,0.015886,2015-01-11
29,402,Salvador Figueroa,29,Male,Hispanic/Latino,2015,"Circle K, 1301 N Eastern Ave",Las Vegas,NV,36.185120,...,19746,41875,52873,0.791992,2,2,22.9,0.140275,0.039349,2015-01-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,148,Elvin Diaz,24,Male,Hispanic/Latino,2015,10 Temple Ave,Hackensack,NJ,40.901131,...,35008,51051,83794,0.609244,1,3,11.1,0.032627,0.348195,2015-05-21
438,331,Michael Lowrey,40,Male,White,2015,1534 N Center Ave,Somerset,PA,40.035759,...,20297,42346,43597,0.971305,2,2,11.2,0.110402,0.164018,2015-05-22
439,70,Caso Jackson,25,Male,Black,2015,13331 Strathmoor St,Detroit,MI,42.385914,...,14177,24539,41184,0.595838,2,1,46.3,0.258065,0.065584,2015-05-23
440,202,James Horn Jr,47,Male,White,2015,SE 650th Rd,Green Ridge,MO,38.657848,...,24705,49649,47223,1.051373,4,3,16.4,0.065678,0.138937,2015-05-23
441,151,Eric Robinson,40,Male,White,2015,135 N Main St,Eagar,AZ,34.113339,...,20644,47821,31476,1.519285,5,3,16.3,0.059302,0.097701,2015-05-23
442,451,Unknown,Unknown,Female,Unknown,2015,6505 Shirley Ave,Austin,TX,32.407139,...,22969,50280,43439,1.157485,5,3,17.9,0.058573,0.100249,2015-05-25
443,33,Anthony Briggs,36,Male,Black,2015,1100 E Gateway Dr SE,Huntsville,AL,34.616840,...,34698,57935,58434,0.991460,3,4,8.9,0.063658,0.422257,2015-05-25
444,337,Millard Tallant III,62,Male,White,2015,17500 Tester Rd,Snohomish,WA,47.837775,...,11405,41000,68381,0.599582,1,2,19.1,0.113813,0.143148,2015-05-26
445,89,Dalton Branch,51,Male,Black,2015,530 Stanley Ave,New York,NY,40.657256,...,21344,34545,46085,0.749593,2,2,20.1,0.106880,0.109860,2015-05-26
446,235,Jessie Williams,24,Male,White,2015,200 John Wesly Blvd,Bossier City,LA,32.517021,...,20396,33898,53248,0.636606,NaN,1,26.4,0.082047,0.166791,2015-05-26
447,368,Randall Torrence,34,Male,White,2015,1225 Quindaro Blvd,Kansas City,KS,39.136246,...,15556,24929,39402,0.632684,1,1,45.3,0.258571,0.036484,2015-05-27
448,161,Feras Morad,20,Male,Unknown,2015,4600 E 15th St,Long Beach,CA,33.785408,...,31776,65912,55909,1.178916,4,4,11.3,0.086559,0.442806,2015-05-27
449,171,Garrett Sandeno,24,Male,White,2015,1701 Ridgecrest Rd,Edmond,OK,35.633228,...,41377,104388,45215,2.308703,5,5,1.3,0.049787,0.596791,2015-05-27
450,416,Simon Hubble,33,Male,White,2015,3600 Emmanuel Way,Alpine,CA,32.750515,...,20164,71929,62962,1.142419,4,4,19.2,0.090909,0.227393,2015-05-27
451,180,Harry Davis,57,Male,White,2015,Sparta Hwy and Oconee Springs Rd,Eatonton,GA,33.343500,...,20760,44902,44764,1.003083,NaN,3,6.6,0.066384,0.085993,2015-05-27
452,408,Scott McAllister,39,Male,Unknown,2015,33 Bayside Pkwy,Middletown,NJ,40.443970,...,34053,77813,84526,0.920581,NaN,5,5.3,0.097529,0.211102,2015-05-27
453,101,Darrell Morgan,60,Male,White,2015,3164 Charlotte Hwy,Lancaster,SC,34.796696,...,22385,41675,42217,0.987162,NaN,2,18.4,0.148903,0.162518,2015-05-28
454,282,Kenneth Dothard,40,Male,Black,2015,900 Bankhead Hwy,Carrollton,GA,33.590656,...,25418,43517,46147,0.943008,NaN,2,17,0.136045,0.179545,2015-05-28
455,290,Kyle Baker,18,Male,White,2015,2800 Longmeadow Dr,Trenton,MI,42.140805,...,26583,60795,41184,1.476180,5,4,6,0.091409,0.236224,2015-05-28
456,206,James Strong,32,Male,Black,2015,10900 E 109th Pl,Northglenn,CO,39.894520,...,30906,55442,56270,0.985285,NaN,3,12.4,0.080360,0.106167,2015-05-28
457,286,Kevin Allen,36,Male,Black,2015,355 Valley Brook Ave,Lyndhurst,NJ,40.812134,...,36305,67109,83794,0.800881,2,4,4.5,0.096801,0.294627,2015-05-29
458,344,Nehemiah Fischer,35,Male,White,2015,Hectorville Rd and Bixby Rd,Mounds,OK,35.841830,...,25231,44573,39156,1.138344,NaN,2,14.1,0.080402,0.125871,2015-05-29
459,381,Robert Box,55,Male,White,2015,108 Fir Canyon Rd,Grants Pass,OR,42.360073,...,23281,48077,37733,1.274137,NaN,3,16,0.138249,0.247411,2015-05-29
460,15,Alexander Rivera,39,Male,Hispanic/Latino,2015,1128 Murfreesboro Pike,Nashville,TN,36.125912,...,20027,25500,47335,0.538713,1,1,36.3,0.088226,0.226815,2015-05-30
461,143,Ebin Proctor,19,Male,Unknown,2015,Yuma Circle,Cottonwood,AZ,34.689529,...,16415,36818,42987,0.856491,1,2,21.7,0.216194,0.139521,2015-05-30
462,374,Richard Davis,50,Male,Black,2015,Tremont St and Morgan St,Rochester,NY,43.147850,...,11558,18833,52394,0.359450,NaN,1,49.9,0.259259,0.096531,2015-05-31
463,205,James Morris,40,Male,Unknown,2015,Juanipero Way and La Loma Dr,Medford,OR,42.311009,...,22947,40781,44005,0.926736,2,2,20.2,0.187595,0.378758,2015-05-31
464,224,Jeffrey Pitts,36,Male,White,2015,3500 Ebenezer Rd,Conyers,GA,33.596124,...,29063,54146,52579,1.029803,NaN,3,8.1,0.140741,0.225638,2015-05-31
465,452,Unknown,Unknown,Male,White,2015,271 Greece Ridge Center Dr,Rochester,NY,32.407139,...,22969,50280,43439,1.157485,5,3,17.9,0.058573,0.100249,2015-06-01
466,197,James Bushey,47,Male,White,2015,2225 Texas Hwy 256 Loop,Palestine,TX,31.774197,...,18238,31815,40653,0.782599,NaN,1,34.8,0.097790,0.162666,2015-06-01

In [24]:
wp = pd.read_csv("data-police-shootings/fatal-police-shootings-data.csv")

In [25]:
wp.shape

(1213, 12)

In [26]:
wp.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level
0,3,Tim Elliot,2015-01-02,shot,gun,53,M,A,Shelton,WA,True,attack
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47,M,W,Aloha,OR,False,attack
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23,M,H,Wichita,KS,False,other
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32,M,W,San Francisco,CA,True,attack
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39,M,H,Evans,CO,False,attack

In [27]:
wp["date"] = pd.to_datetime(wp["date"])

In [28]:
wp.tail()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level
1208,1388,Thurman Reynolds,2016-03-19,shot,gun,21,M,NaN,Chicago,IL,False,attack
1209,1392,Dylan R. Whittaker,2016-03-19,shot,gun,23,M,NaN,White Plains,KY,False,attack
1210,1380,Boyd Keith Ballard,2016-03-20,shot,knife,61,M,NaN,Hopewell,VA,True,attack
1211,1391,Clarence Briggs,2016-03-20,shot,gun,55,M,NaN,Fort Littleton,PA,False,attack
1212,1393,TK TK,2016-03-20,shot,gun,NaN,M,NaN,Fort Wayne,IN,False,attack

In [29]:
wp = wp.iloc[:1212,:]

In [30]:
wp.tail()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level
1207,1387,Joshua Douglas,2016-03-19,shot,undetermined,24,M,NaN,Covington,LA,False,undetermined
1208,1388,Thurman Reynolds,2016-03-19,shot,gun,21,M,NaN,Chicago,IL,False,attack
1209,1392,Dylan R. Whittaker,2016-03-19,shot,gun,23,M,NaN,White Plains,KY,False,attack
1210,1380,Boyd Keith Ballard,2016-03-20,shot,knife,61,M,NaN,Hopewell,VA,True,attack
1211,1391,Clarence Briggs,2016-03-20,shot,gun,55,M,NaN,Fort Littleton,PA,False,attack

Combining WP and Counted

In [31]:
counted = counted.iloc[:,2:]

In [32]:
counted.head()

,name,age,gender,raceethnicity,year,streetaddress,city,state,classification,lawenforcementagency,armed,date
0,Matthew Ajibade,22,Male,Black,2015,1050 Carl Griffin Dr,Savannah,GA,Death in custody,Chatham County Sheriff's Office,No,2015-01-01
1,Lewis Lembke,47,Male,White,2015,4505 SW Masters Loop,Aloha,OR,Gunshot,Washington County Sheriff's Office,Firearm,2015-01-02
2,Tim Elliott,53,Male,Asian/Pacific Islander,2015,600 E Island Lake Dr,Shelton,WA,Gunshot,Mason County Sheriff's Office,Firearm,2015-01-02
3,Michael Kocher Jr,19,Male,White,2015,2600 Kaumualii Hwy,Kaumakani,HI,Struck by vehicle,Kauai Police Department,No,2015-01-03
4,John Quintero,23,Male,Hispanic/Latino,2015,500 North Oliver Ave,Wichita,KS,Gunshot,Wichita Police Department,No,2015-01-03

In [33]:
counted.rename(columns={"raceethnicity":"race", "classification":"cause", "lawenforcementagency":"agency", "streetaddress":"address"}, inplace=True)

In [34]:
wp.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level
0,3,Tim Elliot,2015-01-02,shot,gun,53,M,A,Shelton,WA,True,attack
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47,M,W,Aloha,OR,False,attack
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23,M,H,Wichita,KS,False,other
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32,M,W,San Francisco,CA,True,attack
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39,M,H,Evans,CO,False,attack

In [35]:
wp.gender.value_counts()

M    1158
F      54
Name: gender, dtype: int64

In [36]:
def gender_column(x):
    if x == "M":
        return "Male"
    elif x == "F":
        return "Female"
    else:
        pass

In [37]:
# gender_dictionary = pd.Series({"M":"Male", "F":"Female"})
wp["gender"] = wp.gender.map(gender_column)

In [38]:
wp.gender.value_counts()

Male      1158
Female      54
Name: gender, dtype: int64

In [39]:
wp.race.value_counts()

W    601
B    303
H    202
O     17
A     16
N     13
Name: race, dtype: int64

In [40]:
counted.race.value_counts()

White                     681
Black                     341
Hispanic/Latino           220
Unknown                    52
Asian/Pacific Islander     25
Native American            18
Arab-American               4
Other                       1
Name: race, dtype: int64

In [41]:
def race_column(x):
    if x=="W":
        return "White"
    elif x=="B":
        return "Black"
    elif x=="H":
        return "Hispanic"
    elif x=="O":
        return "Other"
    elif x=="A":
        return "Asian"
    elif x=="N":
        return "Native American"

In [42]:
wp["race"] = wp["race"].map(race_column)

In [43]:
def race_column_counted(x):
    if x=="White":
        return x
    elif x=="Black":
        return x
    elif x=="Hispanic/Latino":
        return "Hispanic"
    elif x=="Asian/Pacific Islander":
        return "Asian"
    else:
        return x

In [44]:
counted["race"] = counted["race"].map(race_column_counted)

In [45]:
counted.race.value_counts()

White              681
Black              341
Hispanic           220
Unknown             52
Asian               25
Native American     18
Arab-American        4
Other                1
Name: race, dtype: int64

In [46]:
len(counted.name.unique())

1330

In [47]:
len(counted.name)

1342

In [114]:
counted.name.value_counts()[:5]

Unknown            7
Robert Edwards     3
Miguel Martinez    2
Jose Rodriguez     2
John Allen         2
Name: name, dtype: int64

In [48]:
counted_names = counted.name
wp_names = wp.name

In [49]:
len(wp_names.unique())

1205

In [50]:
len(wp.name)

1212

In [118]:
wp_names.value_counts()

TK TK                           7
Eric Harris                     2
Curtis James Meyer              1
 Austin Wilburly  Reid          1
Byron Herbert                   1
Nicholas Garner                 1
Mark Gary                       1
David Todd Powell               1
Quincy Reed Reindl              1
Saige Hack                      1
Jose Roman Rodriguez            1
Jamalis Hall                    1
Kaylene Stone                   1
John David Livingston           1
Sully Lanier                    1
Joshua  Jozefowicz              1
Artago Damon Howard             1
Alexander Phillip Long          1
Mario Woods                     1
Miguel Hernandez                1
Michael Tindall                 1
Allen Pacheco                   1
Jerome Nichols                  1
Jamie Croom                     1
Michael Wayne Smashey           1
Vasilios Alexander Katsouras    1
Brandon Lamar Johnson           1
James Joseph Byrd               1
Alexander Myers                 1
Albert Hanson                   1
                               ..
Jesus Quezada Gomez             1
Jason Bryant                    1
James Anderson                  1
Dexter Pernell Bethea           1
Colten Price Marcellus          1
Marcellus Jamarcus Burley       1
James Dudley Barker             1
Scott McAllister                1
Stephen  Cunningham             1
Eugene Smith                    1
Timothy Milliken                1
Marcus Wheeler                  1
Virgil Reynolds                 1
Christopher Anderson            1
Donte Sowell                    1
Raymone M. Davis                1
Neil Scott Stretesky            1
Kenneth Dothard                 1
Fred  Liggett                   1
Gordon Kimbrell                 1
Monique Jenee Deckard           1
Randall Lance Hughes            1
Sahlah Ridgeway                 1
Sam Holmes                      1
Keith Harrison McLeod           1
Christopher Andrews             1
Harrison Lambert                1
Kionte DeShaun Spencer          1
Matthew Watson                  1
Martin  Ryans Jr.               1
Name: name, dtype: int64

In [51]:
names_total = pd.concat([wp_names, counted_names])

In [136]:
counted.columns

Index([u'name', u'age', u'gender', u'race', u'year', u'address', u'city',
       u'state', u'cause', u'agency', u'armed', u'date'],
      dtype='object')

In [137]:
wp.columns

Index([u'id', u'name', u'date', u'manner_of_death', u'armed', u'age',
       u'gender', u'race', u'city', u'state', u'signs_of_mental_illness',
       u'threat_level'],
      dtype='object')

In [52]:
del wp["id"]

In [53]:
wp.rename(columns={"manner_of_death":"cause"}, inplace=True)

In [54]:
wp.columns

Index([u'name', u'date', u'cause', u'armed', u'age', u'gender', u'race',
       u'city', u'state', u'signs_of_mental_illness', u'threat_level'],
      dtype='object')

In [58]:
count_cols = counted.columns.tolist()

In [55]:
wp_columns = wp.columns.tolist()

In [56]:
len(wp_columns)

11

In [59]:
len(count_cols)

12

In [60]:
counted.head()

,name,age,gender,race,year,address,city,state,cause,agency,armed,date
0,Matthew Ajibade,22,Male,Black,2015,1050 Carl Griffin Dr,Savannah,GA,Death in custody,Chatham County Sheriff's Office,No,2015-01-01
1,Lewis Lembke,47,Male,White,2015,4505 SW Masters Loop,Aloha,OR,Gunshot,Washington County Sheriff's Office,Firearm,2015-01-02
2,Tim Elliott,53,Male,Asian,2015,600 E Island Lake Dr,Shelton,WA,Gunshot,Mason County Sheriff's Office,Firearm,2015-01-02
3,Michael Kocher Jr,19,Male,White,2015,2600 Kaumualii Hwy,Kaumakani,HI,Struck by vehicle,Kauai Police Department,No,2015-01-03
4,John Quintero,23,Male,Hispanic,2015,500 North Oliver Ave,Wichita,KS,Gunshot,Wichita Police Department,No,2015-01-03

In [61]:
wp_columns

['name',
 'date',
 'cause',
 'armed',
 'age',
 'gender',
 'race',
 'city',
 'state',
 'signs_of_mental_illness',
 'threat_level']

In [ ]:
wp_columns[0] + wp_columns[4:7] + wp_columns[10] +

In [62]:
counted_reformat = pd.DataFrame.to_csv(counted, "counted_reformat.csv")

In [64]:
counted

,name,age,gender,race,year,address,city,state,cause,agency,armed,date
0,Matthew Ajibade,22,Male,Black,2015,1050 Carl Griffin Dr,Savannah,GA,Death in custody,Chatham County Sheriff's Office,No,2015-01-01
1,Lewis Lembke,47,Male,White,2015,4505 SW Masters Loop,Aloha,OR,Gunshot,Washington County Sheriff's Office,Firearm,2015-01-02
2,Tim Elliott,53,Male,Asian,2015,600 E Island Lake Dr,Shelton,WA,Gunshot,Mason County Sheriff's Office,Firearm,2015-01-02
3,Michael Kocher Jr,19,Male,White,2015,2600 Kaumualii Hwy,Kaumakani,HI,Struck by vehicle,Kauai Police Department,No,2015-01-03
4,John Quintero,23,Male,Hispanic,2015,500 North Oliver Ave,Wichita,KS,Gunshot,Wichita Police Department,No,2015-01-03
5,Matthew Hoffman,32,Male,White,2015,630 Valencia St,San Francisco,CA,Gunshot,San Francisco Police Department,Non-lethal firearm,2015-01-04
6,Kenneth Brown,18,Male,White,2015,NaN,Guthrie,OK,Gunshot,Oklahoma State Police,Firearm,2015-01-04
7,Kenneth Buck,22,Male,Hispanic,2015,E Knox Rd and N Exeter St,Chandler,AZ,Gunshot,Chandler Police Department,Firearm,2015-01-05
8,Michael Rodriguez,39,Male,Hispanic,2015,818 31st St,Evans,CO,Gunshot,Evans Police Department,Other,2015-01-05
9,Frank Smart,39,Male,Black,2015,950 Second Ave,Pittsburgh,PA,Death in custody,Allegheny County Bureau of Corrections,No,2015-01-05
10,Patrick Wetter,25,Male,White,2015,800 Howard St,Stockton,CA,Gunshot,Stockton Police Department,Knife,2015-01-06
11,Brian Pickett,26,Male,Black,2015,1618 E 123rd St,Los Angeles,CA,Taser,Los Angeles County Sheriff's Department,No,2015-01-06
12,Autumn Steele,34,Female,White,2015,104 N Garfield Ave,Burlington,IA,Gunshot,Burlington Police Department,No,2015-01-06
13,Brock Nichols,35,Male,White,2015,2388 E Kansas Hwy 4,Assaria,KS,Gunshot,Saline County Sheriff's Office,Firearm,2015-01-06
14,Leslie Sapp III,47,Male,Black,2015,Redlyn St,Pittsburgh,PA,Gunshot,"US Marshals Service, Pennsylvania State Police...",Non-lethal firearm,2015-01-06
15,Nicholas Brickman,30,Male,White,2015,SE 4th St and Scott Ave,Des Moines,IA,Gunshot,Des Moines Police Department,Firearm,2015-01-07
16,Joseph Caffarello,31,Male,White,2015,6300 Scott St,Rosemont,IL,Gunshot,Rosemont Police Department,Vehicle,2015-01-07
17,Andre Murphy Sr,42,Male,Black,2015,1223 Omaha Ave,Norfolk,NE,Death in custody,Norfolk Police Division,No,2015-01-07
18,Hashim Abdul-Rasheed,41,Male,Black,2015,4600 International Gateway,Columbus,OH,Gunshot,Columbus Police Department,Knife,2015-01-07
19,Ronald Sneed,32,Male,Black,2015,310 Yaupon St,Freeport,TX,Gunshot,Freeport Police Department,Firearm,2015-01-07
20,Artago Howard,36,Male,Black,2015,9661 Strong Hwy,Strong,AR,Gunshot,Union County Sheriff's Office,No,2015-01-08
21,Omarr Jackson,37,Male,Black,2015,Lasalle St and Josephine St,New Orleans,LA,Gunshot,New Orleans Police Department,Firearm,2015-01-08
22,Loren Simpson,28,Male,White,2015,3540 White Buffalo Rd,Huntley,MT,Gunshot,Yellowstone County Sheriff's Office,No,2015-01-08
23,James Barker,42,Male,White,2015,584 E 2nd Ave,Salt Lake City,UT,Gunshot,Salt Lake City Police Department,Other,2015-01-08
24,Thomas Hamby,49,Male,White,2015,2964 W 2125 S,Syracuse,UT,Gunshot,"Syracuse Police Department, Davis County Sheri...",Firearm,2015-01-08
25,Jimmy Foreman,71,Male,White,2015,422 SE 3rd St,England,AR,Gunshot,England Police Department,Firearm,2015-01-09
26,Andy Martinez,33,Male,Hispanic,2015,4400 Tetons Dr,El Paso,TX,Gunshot,El Paso Police Department,Firearm,2015-01-09
27,Brian Barbosa,23,Male,Hispanic,2015,8900 Kauffman Ave,South Gate,CA,Gunshot,South Gate Police Department,Firearm,2015-01-11
28,Salvador Figueroa,29,Male,Hispanic,2015,"Circle K, 1301 N Eastern Ave",Las Vegas,NV,Gunshot,North Las Vegas Police Department,Firearm,2015-01-11
29,Tommy Smith,39,Male,White,2015,224 Circle Dr,Arcola,IL,Gunshot,"Arcola Police Department, Tuscola Police Depar...",Firearm,2015-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...
1312,Dimitri Corcino,39,Male,Hispanic,2016,Mariposa Dr NE,Palm Bay,FL,Gunshot,Palm Bay Police Department,Firearm,2016-03-01
1313,Jorge Gonzalez,22,Male,Hispanic,2016,508 Simmons Dr,Euless,TX,Gunshot,Euless Police Department,Firearm,2016-03-01
1314,Mickey Sweatt,37,Male,White,2016,7300 Home of Grace Dr,Gautier,MS,Gunshot,Gautier Police Department,Firearm,2016-03-01
1315,Travis Bradley,35,Male,White,2016,Althea Ct,Bel Air,MD,Gunshot,Harford County Sheriff's Office,Unknown,2016-03-02
1316,Sergio Ochoa,27,Male,Hispanic,2016,S Lindsay Rd and E Warner Rd,Gilbert,AZ,Gunshot,Mesa Police Department,Knife,2016-03-03
1317,Christopher Kalonji,19,Male,Black,2016,3700 SE Concord Rd,Oak Grove,OR,Gunshot,Clackamas County Sheriff's Office,Firearm,2016-01-28
1318,Daniel Burkhardt,41,Male,White,2016,Spickler Alley,Johnstown,PA,Gunshot,Johnstown Police Department,Knife,2016-03-02
1319,Darrell Bosell,34,Male,White,2016,4600 Genesee St,Cheektowaga,NY,Gunshot,Cheektowaga Police Department,Firearm,2016-03-05
1320,Herbert Ballance,22,Male,White,2016,600 S 23rd St,Beaumont,TX,Gunshot,Beaumont Police Department,Firearm,2016-03-05
1321,John Chamberlain,66,Male,Unknown,2016,NaN,Mt Ida,AR,Gunshot,Montgomery County Sheriff's Office,Unknown,2016-03-04
1322,Osvaldo Torres,41,Male,Hispanic,2016,Tweedy Blvd and Burtis St,South Gate,CA,Gunshot,South Gate Police Department,Firearm,2016-03-06
1323,Philip Vitullo,49,Male,White,2016,3700 Lake Ave,Rochester,NY,Gunshot,Rochester Police Department,Firearm,2016-03-07
1324,James 'Tony' Scott,42,Male,White,2016,E Rosser Ave and N 32nd St,Bismarck,ND,Gunshot,Bismarck Police Department,No,2016-03-06
1325,Mark Minnick,51,Male,White,2016,600 Alameda Rd,Azle,TX,Gunshot,Azle Police Department,Firearm,2016-03-06
1326,Randall Selsor,45,Male,White,2016,504 SW Taylor St,Topeka,KS,Gunshot,United States Marshals Service,Unknown,2016-03-07
1327,Byron Rosas,45,Male,White,2016,S 3rd St and Martha St,San Jose,CA,Gunshot,San Jose Police Department,Knife,2016-03-07
1328,John Charles Graham,42,Male,White,2016,S 1st St,Joliet,MT,Gunshot,Carbon County Sheriff's Office,Firearm,2016-03-07
1329,Brandon Stanley,30,Male,White,2016,700 KY-3094,East Bernstadt,KY,Gunshot,Laurel County Constable's Office,Unknown,2016-03-04
1330,Jeffrey Casale,27,Male,White,2016,Swallowtail Ct,Tampa,FL,Gunshot,Hillsborough County Sheriff's Office,Non-lethal firearm,2016-03-08
1331,Daniel Chavez,41,Male,Hispanic,2016,N Happy Valley Rd and W Texas St,Carlsbad,NM,Gunshot,"Carlsbad Police Department, Eddy County Sherif...",Unknown,2016-03-07
1332,Alex Thompson,37,Male,White,2016,Country Store Rd and US-70,Selma,NC,Taser,Kenly Police Department,No,2016-03-03
1333,Jose Cordoba,28,Male,Hispanic,2016,El Dorado St and E Clay St,Stockton,CA,Taser,Stockton Police Department,No,2016-03-07
1334,Jason Meador,50,Male,White,2016,1200 Douglas Dr,Odessa,TX,Gunshot,Odessa Police Department,Firearm,2016-03-10
1335,Arteair Porter Jr,22,Male,Unknown,2016,Lemmon Dr,Reno,NV,Gunshot,"Reno Police Department, Sparks Police Departme...",Firearm,2016-03-10
1336,Wesley Sheppard,37,Male,White,2016,Popps Ferry Bridge,Biloxi,MS,Gunshot,Biloxi Police Department,Firearm,2016-03-10
1337,Martin Hurtado,21,Male,Unknown,2016,E 68th St and Orcutt Ave,Long Beach,CA,Gunshot,Long Beach Police Department,Firearm,2016-03-10
1338,Unknown,Unknown,Male,Unknown,2016,8950 I-25,Pueblo,CO,Gunshot,Colorado State Patrol,Unknown,2016-03-10
1339,Tyre Privott,25,Male,Black,2016,Chesapeake Blvd and Fishermans Rd,Norfolk,VA,Gunshot,Norfolk Police Department,Firearm,2016-03-11
1340,Manford 'Butch' Moore Jr,51,Male,White,2016,SE 10th St,Rosalia,KS,Gunshot,Butler County Sheriff's Office,Firearm,2016-03-11
1341,Unknown,Unknown,Male,Unknown,2016,5724 Thornton Ave,Newark,CA,Gunshot,Newark (CA) Police Department,Firearm,2016-03-11

In [65]:
wp.shape

(1212, 11)

In [66]:
wp

,name,date,cause,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level
0,Tim Elliot,2015-01-02,shot,gun,53,Male,Asian,Shelton,WA,True,attack
1,Lewis Lee Lembke,2015-01-02,shot,gun,47,Male,White,Aloha,OR,False,attack
2,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23,Male,Hispanic,Wichita,KS,False,other
3,Matthew Hoffman,2015-01-04,shot,toy weapon,32,Male,White,San Francisco,CA,True,attack
4,Michael Rodriguez,2015-01-04,shot,nail gun,39,Male,Hispanic,Evans,CO,False,attack
5,Kenneth Joe Brown,2015-01-04,shot,gun,18,Male,White,Guthrie,OK,False,attack
6,Kenneth Arnold Buck,2015-01-05,shot,gun,22,Male,Hispanic,Chandler,AZ,False,attack
7,Brock Nichols,2015-01-06,shot,gun,35,Male,White,Assaria,KS,False,attack
8,Autumn Steele,2015-01-06,shot,unarmed,34,Female,White,Burlington,IA,False,other
9,Leslie Sapp III,2015-01-06,shot,toy weapon,47,Male,Black,Knoxville,PA,False,attack
10,Patrick Wetter,2015-01-06,shot and Tasered,knife,25,Male,White,Stockton,CA,False,attack
11,Ron Sneed,2015-01-07,shot,gun,31,Male,Black,Freeport,TX,False,attack
12,Hashim Hanif Ibn Abdul-Rasheed,2015-01-07,shot,knife,41,Male,Black,Columbus,OH,True,other
13,Nicholas Ryan Brickman,2015-01-07,shot,gun,30,Male,White,Des Moines,IA,False,attack
14,Omarr Julian Maximillian Jackson,2015-01-07,shot,gun,37,Male,Black,New Orleans,LA,False,attack
15,Loren Simpson,2015-01-08,shot,vehicle,28,Male,White,Huntley,MT,False,undetermined
16,James Dudley Barker,2015-01-08,shot,shovel,42,Male,White,Salt Lake City,UT,False,attack
17,Artago Damon Howard,2015-01-08,shot,unarmed,36,Male,Black,Strong,AR,False,attack
18,Thomas Hamby,2015-01-08,shot,gun,49,Male,White,Syracuse,UT,False,attack
19,Jimmy Foreman,2015-01-09,shot,gun,71,Male,White,England,AR,False,attack
20,Andy Martinez,2015-01-09,shot,gun,33,Male,Hispanic,El Paso,TX,False,attack
21,Tommy Smith,2015-01-11,shot,gun,39,Male,White,Arcola,IL,True,attack
22,Brian Barbosa,2015-01-11,shot,gun,23,Male,Hispanic,South Gate,CA,False,attack
23,Salvador Figueroa,2015-01-11,shot and Tasered,gun,29,Male,Hispanic,North Las Vegas,NV,False,attack
24,John Edward O'Keefe,2015-01-13,shot,gun,34,Male,White,Albuquerque,NM,False,attack
25,Richard McClendon,2015-01-13,shot,knife,43,Male,White,Jourdanton,TX,True,other
26,Marcus Golden,2015-01-14,shot,vehicle,24,Male,Black,St. Paul,MN,False,attack
27,Michael Goebel,2015-01-14,shot,vehicle,29,Male,White,Franklin County,MO,False,attack
28,Mario Jordan,2015-01-14,shot,gun,34,Male,Black,Chesapeake,VA,True,attack
29,Talbot Schroeder,2015-01-14,shot,knife,75,Male,White,Old Bridge,NJ,False,attack
...,...,...,...,...,...,...,...,...,...,...,...
1182,"Manford ""Butch"" Moore Jr.",2016-03-11,shot,gun,51,Male,White,Rosalia,KS,True,attack
1183,Jack Goodman,2016-03-11,shot,knife,46,Male,None,Clinton,IL,True,other
1184,Peter Gaines,2016-03-12,shot and Tasered,unarmed,37,Male,Black,Houston,TX,False,other
1185,TK TK,2016-03-12,shot and Tasered,unarmed,NaN,Male,None,Houston,TX,False,attack
1186,Gevork Alachadzhyan,2016-03-13,shot,vehicle,45,Male,White,Glendale,CA,True,attack
1187,Jose Raul Cruz,2016-03-13,shot,undetermined,16,Male,Hispanic,Addison,TX,False,undetermined
1188,Joshua Grubb,2016-03-13,shot,undetermined,30,Male,White,Lenoir City,TN,False,other
1189,Wesley Chad Deerman,2016-03-13,shot,gun,26,Male,White,Piedmont,AL,False,attack
1190,TK TK,2016-03-13,shot,gun,NaN,Male,None,Chester,PA,False,attack
1191,Amy Jean McCoy,2016-03-13,shot,hammer,38,Female,None,Vancouver,WA,False,attack
1192,Jacai Colson,2016-03-13,shot,gun,28,Male,Black,Landover,MD,False,other
1193,Lamar Harris,2016-03-14,shot,gun,29,Male,Black,Chicago,IL,False,attack
1194,Joseph Harris,2016-03-15,shot,gun,34,Male,None,Russellville,KY,False,undetermined
1195,Daniel J. Wooters,2016-03-15,shot,knife,38,Male,White,Evansville,IN,False,other
1196,Ed Russell McIver,2016-03-15,shot,gun,43,Male,White,Fort Worth,TX,False,undetermined
1197,Cristian Rene Medina,2016-03-16,shot,unarmed,23,Male,None,Florence,CA,True,undetermined
1198,Eric Hernandez,2016-03-16,shot,gun,33,Male,Hispanic,San Antonio,TX,True,undetermined
1199,Dennis Penny,2016-03-16,shot,gun,40,Male,None,Anson County,NC,False,attack
1200,Map Kong,2016-03-17,shot,gun,38,Male,None,Burnsville,MN,False,undetermined
1201,Sunny Chin,2016-03-17,shot,gun,53,Male,Asian,Tampa,FL,False,attack
1202,Scott Bennett,2016-03-17,shot,gun,29,Male,None,Houston,TX,False,undetermined
1203,Christopher Nelms,2016-03-17,shot,gun,30,Male,None,Houston,TX,False,undetermined
1204,Michael Mallet,2016-03-18,shot,gun,49,Male,None,Byron,CA,True,attack
1205,Ryan Shorak,2016-03-18,shot,gun,37,Male,White,Ohioville,PA,False,attack
1206,India Beaty,2016-03-19,shot,toy weapon,25,Female,Black,Norfolk,VA,False,undetermined
1207,Joshua Douglas,2016-03-19,shot,undetermined,24,Male,None,Covington,LA,False,undetermined
1208,Thurman Reynolds,2016-03-19,shot,gun,21,Male,None,Chicago,IL,False,attack
1209,Dylan R. Whittaker,2016-03-19,shot,gun,23,Male,None,White Plains,KY,False,attack
1210,Boyd Keith Ballard,2016-03-20,shot,knife,61,Male,None,Hopewell,VA,True,attack
1211,Clarence Briggs,2016-03-20,shot,gun,55,Male,None,Fort Littleton,PA,False,attack

In [67]:
test_concat = pd.concat([wp, counted])

In [85]:
wp.head()

,name,date,cause,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,year
0,Tim Elliot,2015-01-02,shot,gun,53,Male,Asian,Shelton,WA,True,attack,2015
1,Lewis Lee Lembke,2015-01-02,shot,gun,47,Male,White,Aloha,OR,False,attack,2015
2,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23,Male,Hispanic,Wichita,KS,False,other,2015
3,Matthew Hoffman,2015-01-04,shot,toy weapon,32,Male,White,San Francisco,CA,True,attack,2015
4,Michael Rodriguez,2015-01-04,shot,nail gun,39,Male,Hispanic,Evans,CO,False,attack,2015

In [ ]:
new_list

In [86]:
counted.head()

,name,age,gender,race,year,address,city,state,cause,agency,armed,date
0,Matthew Ajibade,22,Male,Black,2015,1050 Carl Griffin Dr,Savannah,GA,Death in custody,Chatham County Sheriff's Office,No,2015-01-01
1,Lewis Lembke,47,Male,White,2015,4505 SW Masters Loop,Aloha,OR,Gunshot,Washington County Sheriff's Office,Firearm,2015-01-02
2,Tim Elliott,53,Male,Asian,2015,600 E Island Lake Dr,Shelton,WA,Gunshot,Mason County Sheriff's Office,Firearm,2015-01-02
3,Michael Kocher Jr,19,Male,White,2015,2600 Kaumualii Hwy,Kaumakani,HI,Struck by vehicle,Kauai Police Department,No,2015-01-03
4,John Quintero,23,Male,Hispanic,2015,500 North Oliver Ave,Wichita,KS,Gunshot,Wichita Police Department,No,2015-01-03

In [69]:
test_concat.shape

(2554, 14)

In [79]:
wp["date"] = pd.to_datetime(wp["date"])

In [82]:
wp["year"] = wp["date"].dt.year

In [83]:
wp.columns

Index([u'name', u'date', u'cause', u'armed', u'age', u'gender', u'race',
       u'city', u'state', u'signs_of_mental_illness', u'threat_level',
       u'year'],
      dtype='object')

In [84]:
counted.columns

Index([u'name', u'age', u'gender', u'race', u'year', u'address', u'city',
       u'state', u'cause', u'agency', u'armed', u'date'],
      dtype='object')

In [87]:
counted.agency.value_counts()

Los Angeles Police Department                  27
Los Angeles County Sheriff's Department        19
Phoenix Police Department                      12
Houston Police Department                      11
Chicago Police Department                      11
Unknown                                        11
New York Police Department                     10
Indianapolis Metropolitan Police Department     9
Las Vegas Metropolitan Police Department        9
Oklahoma City Police Department                 9
Austin Police Department                        8
San Francisco Police Department                 8
San Diego Police Department                     8
Miami-Dade Police Department                    7
San Antonio Police Department                   7
San Jose Police Department                      7
Mesa Police Department                          7
Dallas Police Department                        7
Riverside County Sheriff's Department           7
Bakersfield Police Department                   7
Long Beach Police Department                    6
Denver Police Department                        6
Jacksonville Sheriff's Office                   6
Pennsylvania State Police                       6
Fort Worth Police Department                    6
Aurora Police Department                        5
Baltimore County Police Department              5
Anaheim Police Department                       5
California Highway Patrol                       5
Fresno Police Department                        5
                                               ..
Chatham County Sheriff's Office                 1
Green Bay Police Department                     1
Detroit Police Department                       1
Canyon County Sheriff's Office                  1
Providence Police Department                    1
Mission Police Department                       1
Arapahoe County Sheriff's Office                1
Potsdam Police Department                       1
Azusa Police Department                         1
Navajo Police Department                        1
Scottsdale Police Department                    1
Weston Police Department                        1
Greeley Police Department                       1
Livingston Police Department                    1
Klamath County Sheriff's Office                 1
North Port Police Department                    1
Port Wentworth Police Department                1
Azle Police Department                          1
Los Angeles Sheriff's Department                1
Newport News Police Department                  1
Gautier Police Department                       1
Pennsylvania state constable                    1
Colorado State Patrol                           1
Massachusetts State Police                      1
Lynn County Sheriff's Office                    1
Franklin Parish Sheriff's Office                1
Lake Jackson Police Department                  1
Pennington County Sheriff's Office              1
Tuscaloosa Police Department                    1
Boulder Police Department                       1
Name: agency, dtype: int64

In [88]:
c_name_lst = list(counted.name)

In [91]:
wp_name_lst = list(wp.name)

In [92]:
len(wp_name_lst+c_name_lst)

2554

In [93]:
len(set(wp_name_lst+c_name_lst))

1803

In [95]:
wp.name.value_counts()[:4]

TK TK                     7
Eric Harris               2
Curtis James Meyer        1
 Austin Wilburly  Reid    1
Name: name, dtype: int64

In [96]:
wp[wp["name"]== "Eric Harris"]

,name,date,cause,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,year
249,Eric Harris,2015-04-02,shot,unarmed,44,Male,Black,Tulsa,OK,False,other,2015
1092,Eric Harris,2016-02-08,shot,vehicle,22,Male,Black,New Orleans,LA,False,undetermined,2016

In [97]:
wp["name"][249] ="Eric Harris Tulsa OK"

/Users/georgemcintire/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [98]:
wp.iloc[249,:2]

name    Eric Harris Tulsa OK
date     2015-04-02 00:00:00
Name: 249, dtype: object

In [99]:
wp["name"][1092] = "Eric Harris New Orleans LA"

/Users/georgemcintire/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [102]:
counted.name.value_counts()[:7]

Unknown            7
Robert Edwards     3
Miguel Martinez    2
Jose Rodriguez     2
John Allen         2
Eric Harris        2
Corey Achstein     1
Name: name, dtype: int64

In [ ]:
counted[counted["name"] == "Robert Edwards"]

In [103]:
!ls

538 Linear regression
538_README.md
538_analysis_notebook.ipynb
538_police_killings.csv
COUNTED_README.txt
Counted_Data_Analysis.ipynb
TK TK TK.ipynb
Ultimate database 2013-2015.ipynb
WP_Fatal_Police_Shootings.csv
Washington Post Data Analysis.ipynb
ardpdqp.pdf
counted_reformat.csv
counted_reformat.numbers
county_ids.html
data-police-shootings
fatal_encounters_data.ipynb
fatal_encounters_form_responses.csv
graphics
mapping-violence.html
mapping_violence_13_15_Police Killings.csv
police-locals.csv
state_np.csv
state_np.pkl
state_per_capita_rate.csv
the-counted-2015.csv
the-counted-2016.csv

In [104]:
fe = pd.read_csv("fatal_encounters_form_responses.csv")

In [108]:
fe.iloc[140:150,12:]

,Agency responsible for death,Cause of death,A brief description of the circumstances surrounding the death,Official disposition of death (justified or other),Link to news article or photo of official document,Symptoms of mental illness?,Unique identifier/submitted by,Email address,Date&Description,11883,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
140,Hawaii Police Department,Gunshot,Yanagawa was wanted for his alleged involvemen...,Pending investigation,http://westhawaiitoday.com/news/local-news/pol...,No,NaN,NaN,2/9/2016: Yanagawa was wanted for his alleged ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,Windom Police Department,Gunshot,Police were called to a disturbance. Shots wer...,Suicide,http://www.twincities.com/2016/02/08/man-dead-...,Yes,NaN,NaN,2/8/2016: Police were called to a disturbance....,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,Jefferson Parish Sheriff's Office,Gunshot,Police said Harris was pointing a gun at peopl...,Pending investigation,http://www.ksla.com/story/31172316/jp-deputies...,No,NaN,NaN,2/8/2016: Police said Harris was pointing a gu...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,"Chester Police Department, Upland Police Depar...",Gunshot,An officer tried to stop an SUV driven Longer ...,Pending investigation,http://www.delcotimes.com/article/DC/20160208/...,No,NaN,NaN,2/8/2016: An officer tried to stop an SUV driv...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,Austin Police Department,Gunshot,"According to Austin police, officers responded...",Pending investigation,http://www.kvue.com/story/news/local/2016/02/0...,Unknown,NaN,NaN,"2/8/2016: According to Austin police, officers...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,Lonoke County Sheriff's Office,Gunshot,Officers were sent to a domestic disturbance. ...,Pending investigation,http://katv.com/news/local/lonoke-county-deput...,No,NaN,NaN,2/7/2016: Officers were sent to a domestic dis...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,Columbus Police Department,Gunshot,Officers were dispatched to the 700 block of W...,Pending investigation,http://nbc4i.com/2016/02/07/cpd-suspect-killed...,No,NaN,NaN,2/7/2016: Officers were dispatched to the 700 ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,"Ocean County Sheriff's Office, Manchester Town...",Gunshot,Michael Laniado allegedly held his girlfriend ...,Pending investigation,http://patch.com/new-jersey/manchester-nj/brea...,No,NaN,NaN,2/6/2016: Michael Laniado allegedly held his g...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,Kenton Police Department,Gunshot,Police went to a disturbance at a home in Kent...,Pending investigation,http://nbc4i.com/2016/02/06/officer-shot-suspe...,No,NaN,NaN,2/6/2016: Police went to a disturbance at a ho...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,Los Angeles Police Department,Gunshot,"Details are sketchy, but officers were followi...",Pending investigation,NaN,No,NaN,NaN,"2/6/2016: Details are sketchy, but officers we...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN